#!/bin/bash

# Check if amulet is installed before adding repository and updating apt-get.
#dpkg -s amulet
#if [ $? -ne 0 ]; then
    sudo add-apt-repository -y ppa:juju/stable
    sudo add-apt-repository -y ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install -y amulet python-requests python3.4
#fi
# Install any additional python packages or testing software here.

